/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as EarlyCustomersRouteImport } from './routes/early-customers'
import { Route as HowWeBuildRouteImport } from './routes/how-we-build'
import { Route as UpcomingProductsRouteImport } from './routes/upcoming-products'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EarlyCustomersRoute = EarlyCustomersRouteImport.update({
  id: '/early-customers',
  path: '/early-customers',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeBuildRoute = HowWeBuildRouteImport.update({
  id: '/how-we-build',
  path: '/how-we-build',
  getParentRoute: () => rootRouteImport,
} as any)
const UpcomingProductsRoute = UpcomingProductsRouteImport.update({
  id: '/upcoming-products',
  path: '/upcoming-products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/early-customers': typeof EarlyCustomersRoute
  '/how-we-build': typeof HowWeBuildRoute
  '/upcoming-products': typeof UpcomingProductsRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/early-customers': typeof EarlyCustomersRoute
  '/how-we-build': typeof HowWeBuildRoute
  '/upcoming-products': typeof UpcomingProductsRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/early-customers': typeof EarlyCustomersRoute
  '/how-we-build': typeof HowWeBuildRoute
  '/upcoming-products': typeof UpcomingProductsRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/early-customers'
    | '/how-we-build'
    | '/upcoming-products'
    | '/products/$slug'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/early-customers'
    | '/how-we-build'
    | '/upcoming-products'
    | '/products/$slug'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/early-customers'
    | '/how-we-build'
    | '/upcoming-products'
    | '/products/$slug'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EarlyCustomersRoute: typeof EarlyCustomersRoute
  HowWeBuildRoute: typeof HowWeBuildRoute
  UpcomingProductsRoute: typeof UpcomingProductsRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/early-customers': {
      id: '/early-customers'
      path: '/early-customers'
      fullPath: '/early-customers'
      preLoaderRoute: typeof EarlyCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-build': {
      id: '/how-we-build'
      path: '/how-we-build'
      fullPath: '/how-we-build'
      preLoaderRoute: typeof HowWeBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upcoming-products': {
      id: '/upcoming-products'
      path: '/upcoming-products'
      fullPath: '/upcoming-products'
      preLoaderRoute: typeof UpcomingProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EarlyCustomersRoute: EarlyCustomersRoute,
  HowWeBuildRoute: HowWeBuildRoute,
  UpcomingProductsRoute: UpcomingProductsRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
